services:
  subscription-service:
    build:
      context: ./subscription-service
    container_name: subscription-service
    ports:
      - "5000:5000"
    env_file:
      - ./subscription-service/.env
    depends_on:
      - subscription-db

  subscription-db:
    image: postgres:16.9
    container_name: subscription-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: subscription-db
    volumes:
      - subscription-db-data:/var/lib/postgresql/data

  polling-service:
    build:
      context: ./polling-service
    container_name: polling-service
    ports:
      - "5001:5001"
    env_file:
      - ./polling-service/.env
    depends_on:
      - polling-queue-db

  polling-queue-db:
    image: postgres:16.9
    container_name: polling-queue-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: polling-queue-db
    volumes:
      - polling-queue-db-data:/var/lib/postgresql/data

  receiver-service:
    build:
      context: ./receiver-service
    container_name: receiver-service
    ports:
      - "5002:5002"
    env_file:
      - ./receiver-service/.env
    depends_on:
      - receiver-db

  receiver-db:
    image: postgres:16.9
    container_name: receiver-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: receiver-db
    volumes:
      - receiver-db-data:/var/lib/postgresql/data

volumes:
  subscription-db-data:
  polling-queue-db-data:
  receiver-db-data: