services:
  subscription-service:
    build:
      context: ./subscription-service
    container_name: subscription-service
    ports:
      - "5000:5000"
    env_file:
      - ./subscription-service/.env
    depends_on:
      - subscription-db

  subscription-db:
    image: postgres:16.9
    container_name: subscription-db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: subscription-db
    ports: 
      - "5432:5432"
    volumes:
      - subscription-db-data:/var/lib/postgresql/data

volumes:
  subscription-db-data: